### PR TITLE
fix(115):  FrozenError on BuildableSearch

### LINKED ISSUE #115: FrozenError When Building Query
Hi there!

We noticed an issue with this gem when used with the `frozen_string_literal: true` directive.

We're able to reproduce the issue as follows:

```ruby
# frozen_string_literal: true

require 'aws-record'

class Foo
  include Aws::Record

  set_table_name(ENV['DB_TABLE_NAME'])
  string_attr(:pk, hash_key: true)
  string_attr(:sk, range_key: true)

  class << self
    def query_by_id(id)
      build_query.key_expr(
        ':pk = ? AND begins_with(sk, ?)',
        "USER##{id}",
        'PROFILE#'
      )
        .consistent_read(false)
        .scan_ascending(false)
        .complete!
    end
  end
end

Foo.query_by_id('1').to_a # => FrozenError (can't modify frozen String: ":pk = ? AND begins_with(sk, ?)")
```

It looks like the gem uses `gsub!` in a few locations internally on the query string: https://github.com/aws/aws-sdk-ruby-record/blob/6061abc4f6d2cb1696e38a917770c19b172d0c49/lib/aws-record/record/buildable_search.rb#L235. These calls mutate the input query string which is incompatible with `frozen_string_literal: true`.

Is it possible to use non-mutative method calls internally?

Thanks!

### PR DESCRIPTION
**Pull request by jessedoyle**
Hello!

I noticed that building queries dynamically via `#build_query` will mutate the underlying query string passed in to the `key_expr` method when Aws::Record is creating the prepared statement.

When using the `frozen_string_literal: true` directive, this causes the following exception to be raised:

```
FrozenError (can't modify frozen String: ...)
```

This PR resolves the issue by modifying the private methods that create a prepared statement to return a new string instance rather than mutate the underlying string.

*Issue #, if available:* 

resolves #115.

*Description of changes:*

* Write a failing test for the issue described in #115.
* Add `vendor/bundle` and `.bundle` to the gitignore file for those
  of us that vendorize their dependencies.
* Fix up some whitespace issues in CONTRIBUTORS.md
* Modify the private methods of `_apply_values` and
  `_key_pass` to return a new string instance of a
  prepared statement after each pass - this way we can
  avoid calling mutative string methods (i.e. `String#gsub!`)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by alextwoods** [comment]
Thanks for submitting this!  Overall the change looks reasonable, but it looks like our travis based CI test suite has stopped working.  We're working on fixing that and should be able to review this week.

**Comment by mullermp** [comment]
I've migrated to GH actions. Can we force a rebuild somehow?

**Comment by jessedoyle** [comment]
@mullermp - I’ll rebase that upstream changes into the branch. That should trigger a rebuild!

**Comment by jessedoyle** [comment]
@mullermp - Rebased! Looks like GitHub Actions just needs approval to run.

**Review by alextwoods — APPROVED** [review]

**Comment by mullermp** [comment]
Thanks for your contribution. We will release this sometime this week.

**Pull request merged**
