### PR TITLE
Fix for #empty? responding correctly to empty responses

### PR DESCRIPTION
**Pull request by pye2k**
Pull request for #35.

### CODE REVIEW

**Comment by awood45** [comment]
I'm checking this against some integration test cases I have now. Pagination in the query/scan operations could produce new edge cases to test for.

**Comment by awood45** [comment]
Actually, I'm pretty sure for a couple reasons that the test case I have in mind is both impossible (service won't do it) and already covered, but let's add this to make sure we handle it gracefully, including going forward. Test case is like so:

```ruby
it "is not empty" do
  stub_client.stub_responses(:scan, truncated_resp, resp_empty)
  c = ItemCollection.new(
    :scan,
    { table_name: "TestTable" },
      model,
      stub_client
  )
  expect(c.empty?).to be_falsy
end
```

You'll need to expand the scope of where `truncated_resp` is available to test this. This ensures that if we aren't only checking the last page. With the current implementation, I don't think we even get to the second client call.

**Comment by awood45** [comment]
Actually, I'll just add that before pushing a release. Thanks!

**Comment by pye2k** [comment]
:+1:

**Comment by awood45** [comment]
I added additional support for an edge case related to empty pages followed by pages with content, which is possible in scan operations.

I also added documentation warnings, given that this can easily do full table scans.

**Pull request merged**
